### ISSUE TITLE
grep statement falsely finds partial matches 

### ISSUE THREAD

**Issue by manfredsc** [fbuihuu/find-legacy-symlinks#2]
I have
```
#> ls -l /dev/disk/by-id/ |grep "nvme0n1$"
lrwxrwxrwx 1 root root 13 2022-07-25 11:53 /dev/disk/by-id/-Samsung_SSD_970_PRO_512GB_S463NF0K512719M -> ../../nvme0n1
lrwxrwxrwx 1 root root 13 2022-07-25 11:53 /dev/disk/by-id/nvme-20025385581b03fdf -> ../../nvme0n1
lrwxrwxrwx 1 root root 13 2022-07-25 11:53 /dev/disk/by-id/nvme-SNVMe_Samsung_SSD_970_S463NF0K512719M -> ../../nvme0n1
lrwxrwxrwx 1 root root 13 2022-07-25 11:53 /dev/disk/by-id/nvme-Samsung_SSD_970_PRO_512GB_S463NF0K512719M -> ../../nvme0n1
lrwxrwxrwx 1 root root 13 2022-07-25 11:53 /dev/disk/by-id/nvme-eui.0025385581b03fdf -> ../../nvme0n1
```

When treating "-Samsung_SSD_970_PRO_512GB_S463NF0K512719M" in the script,
the grep statement catches also
`/dev/disk/by-id/nvme-Samsung_SSD_970_PRO_512GB_S463NF0K512719M-part1  /scratch        xfs        defaults 1 2`
in /etc/fstab, which is not correct.

Something like
`grep -q -e "[\s/]"$(basename -- "$l") $f && `
in line 97 would work for me, but I don't know if this would miss some cases.

**Comment by fbuihuu** [comment]
Thanks for reporting.

I think simply prefixing the grep pattern with `/` should work since `$symlinks` stores the absolute paths of the deprecated symlinks. I don't see why we would also need to check for a space...

Hence doing `grep -q -e /$(basename -- "$l") $f ` should work, shouldn't it ?

**Comment by fbuihuu** [comment]
And just in case the symlink path would contain spaces, I would enclosed the grep pattern inside double quotes:

`grep -q -e "/$(basename -- "$l")" $f`

WDYT ?

**Comment by manfredsc** [comment]
I was not sure if the omission of "/" was on purpose or not. Yes I think your latter proposal should work.

**Comment by fbuihuu** [comment]
Thanks for the feedback, I'll push this change.
