### ISSUE TITLE
Script not functional due to "set -e"

### ISSUE THREAD

**Issue by manfredsc** [fbuihuu/find-legacy-symlinks#3]
Due to "set -e", the test `[ "$settle" != "--settle" ] ` may become false and stop the whole thing.

This can be fixed by either appending "|| true", or by using an "if" statement:
```
    [ "$settle" != "--settle" ] &&
            udevadm settle --timeout=10 || true
```

```
    if [ "$settle" != "--settle" ]; then
      udevadm settle --timeout=10
    fi
```

**Comment by fbuihuu** [comment]
I don't think there's any issue here. The script exits only if `udevadm settle` (i.e. the last commands of the && list) fails, see the bash man page:

> The shell does not exit if the command that fails is part of  the command list immediately following a while or until keyword, part of the test following the if or elif reserved  words, part of any command executed in a && or || list except the command following the final && or ||,

**Comment by manfredsc** [comment]
Well, I noticed it with first-hand experience. I wanted to know the canonical names of my new NVME-SSD,
and wondered why the script does nothing. It stopped at `"$settle" != "--settle"`. Removing "set -e" or doing
a change as suggested made it work. I was astonished myself. Might be a bash bug. I have bash 4.4.23 and
udev 249.

**Comment by fbuihuu** [comment]
Can you still reproduce this behavior ?

If so I would suggest to write a test case with the misbehaving part isolated and then replace `udevadm settle` with `/bin/true` for example.

**Comment by manfredsc** [comment]
Yes.
Minimal reproducer (Leap 15.4):
```
#!/usr/bin/bash

bash --version | head -n1

set -e

settle="--settle"
[ "$settle" != "--settle" ]
echo "At the end"

exit
```
gives:
`GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)`


Variant with function calls:
```
#!/usr/bin/bash

bash --version | head -n1

set -e

func ()
{
  echo "In function body"
  settle="--settle"
  [ "$settle" != "--settle" ]
}

func &  # subshells clear "-e" when not in posix mode
wait
echo "After first call"

func
echo "At the end"

exit
```
gives:
```
GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)
In function body
After first call
In function body
```

**Comment by fbuihuu** [comment]
> Yes. Minimal reproducer (Leap 15.4):
> 
> ```
> #!/usr/bin/bash
> 
> bash --version | head -n1
> 
> set -e
> 
> settle="--settle"
> [ "$settle" != "--settle" ]

You need to make `[ "$settle" != "--settle" ]` part of a `&&` command list.

Something like `[ "$settle" != "--settle" ] && /bin/true`

**Comment by manfredsc** [comment]
OK, with `[ "$settle" != "--settle" ] && /bin/true` the minimal reproducer works for me and
prints "At the end".
But the function variant gives still the same result, i.e. no "At the end" is printed.

**Comment by fbuihuu** [comment]
ouch yeah I see now the problem, will fix it ASAP

**Comment by fbuihuu** [comment]
@manfredsc fix available, thanks for the report !
